### ISSUE TITLE
[NTR] Add resolution definitions

### ISSUE THREAD

**Issue by Zack-83** [NFDI4Chem/VibrationalSpectroscopyOntology#125]
There are four types of data resolution: spatial, spectral, radiometric and temporal. Many instruments can capture one or two types of resolution simultaneously, yet it is rare to find equipment capable of delivering on all four types. This phenomenon is known as the resolution trade-off. Most instruments measure the most commonly used types of resolutions: spatial and spectral. Together, spatial and spectral resolutions allow scientists to quantitatively measure factors such as color, space and detail.

## Preferred term labels and textual definitions
* resolution =def: A [physical quality](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001018) of a measurement device that expresses (realizes) the device's capacity to distinguish between two distinct but closely related measurements of the same physical quality or type, often quantified as the smallest detectable difference (resolution interval) between measured values. 
* resolution interval =def: A [data item](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000027) that quantifies a resolution, by representing the minimum measurable difference between two measurements of the same physical quality or type, such that the measurements can be distinguished as different.
   * spatial resolution interval =def: A resolution interval that quantifies the minimum distance between two points such that they can be considered two separate points in a given microscope under specific experimental parameters.
      * lateral resolution interval as angle =def: A spatial resolution interval that quantifies the minimum angular separation between two points on a plane orthogonal to the light ray, expressed as an angle centered in the lens (Formula: δθ = 1.22 * λ / D).
      * lateral resolution interval as length =def: A spatial resolution interval that quantifies the minimum linear separation between two points on a plane orthogonal to the light ray, expressed as the distance from the center of the optical spot (Formula: δr = 0.61 * λ / NA).
      * axial resolution interval as length =def: A spatial resolution interval that quantifies the minimum measurable separation between two points along the axis of propagation of the light ray, expressed as a linear distance (Formula: δz = 2 ⋅ n ⋅ λ / NA²).
      * diffraction limit =def: A spatial resolution interval that quantifies the theoretical maximum spatial resolution achievable by an optical system, constrained by the diffraction of light.
   * spectral resolution interval =def: A resolution interval that quantifies the minimum separation between two narrow peaks in a spectrum such that they can be distinguished as two separate peaks.
      * spectral resolution interval as wavelength =def: A spectral resolution interval that quantifies the minimum separation between two wavelengths such that they can be distinguished as different (Formula: δλ = λ / (n * N)).
      * spectral resolution interval as wavenumber =def:  A spectral resolution interval that quantifies the minimum separation between two wavenumbers such that they can be distinguished as different (Formula: δν~ = δλ / λ²).
      * spectral resolution interval as frequency =def:  A spectral resolution interval that quantifies the minimum separation between two energy levels such that they can be distinguished as different (Formula: δE = h * δν = h * c * δν~ = h * c * δλ / λ²).
      * spectral resolution interval as energy =def:  Spectral resolution expressed as difference of energies. δE
   * radiometric resolution interval =def: A resolution interval that quantifies the minimum difference in irradiated energy, often coded as gray level in a grayscale or look-up-table (LUT).
   * temporal resolution =def: A resolution interval that quantifies the temporal separation between two measurements or frames, often expressed as the inverse of the frame rate. In techniques where temporal resolution is not directly derived from frame rate, it quantifies the minimum temporal interval between two resolvable events.   
* resolution power =def: A [ratio](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSTATO_0000184) that quantifies the ability of a measurement device to distinguish between small differences in measurement values, expressed as the ratio between a typical measurement datum and the corresponding resolution interval.

## Synonyms

...

## Textual definition

s. above

## Link to [CHARISMA Wiki equivalent](https://wiki.charisma.ideaconsult.net/wiki/List_of_all_terms)

- https://wiki.charisma.ideaconsult.net/wiki/Item:Q22 Resolution (Raman)  
- https://wiki.charisma.ideaconsult.net/wiki/Item:Q200 Spectral resolution  
- https://wiki.charisma.ideaconsult.net/wiki/Item:Q198 Pixel resolution 

None of them is exhausting.

## Suggested parent term

- resolution - [PATO:physical quality](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001018)
- resolution interval - [IAO:data item](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000027)
- resolution power - [STATO:ratio](https://terminology.nfdi4chem.de/ts/ontologies/vibso/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FSTATO_0000184) 

## Examples

Please provide a more detailed description that examplifies how the term is supposed to be used, in terms of what it is suppose to repesent (e.g. a concept or a relation).

## Attribution

If you would like a nanoattribution, please indicate your ORCID id

## Sources
* https://www.hunterlab.com/blog/what-is-spectral-resolution/ --> https://en.wikipedia.org/wiki/Image_resolution#Types  
* https://phys.libretexts.org/Bookshelves/Mathematical_Physics_and_Pedagogy/Computational_Physics_(Chong)/11%3A_Discrete_Fourier_Transforms/11.02%3A_Spectral_Resolution_and_Range
* https://en.wikipedia.org/wiki/Optical_resolution
* http://vikdhillon.staff.shef.ac.uk/teaching/phy217/instruments/phy217_inst_dispersion.html
* https://www.azom.com/article.aspx?ArticleID=13369 https://www.ossila.com/pages/spectrometer-resolution

**Comment by Zack-83** [comment]
@https://github.com/Stefano-Luin Stiamo cercando di mettere in ordine tra le diverse definizioni di "risoluzione". Vuoi contribuire anche tu?

**Comment by StroemPhi** [comment]
we will need to look up "sectral dispersion" as defined in CHARISMA, once it is in the https://wiki.charisma.ideaconsult.net/wiki/List_of_all_terms

**Comment by Stefano-Luin** [comment]
Resolution in science is, in general, the minimum difference between two measurements so that they can be resolved (i.e., they can be considered different).
In microscopy, it is the minimum distance between two points so that they can be considered two separate points in a certain microscope with given experimental parameters.
In spectroscopy, it is the minimum distance between two very narrow peaks so that they can be seen as two separate peak.
In radiometry, it is the minimum difference of irradiated energy to which can be (or are) given different "values" (e.g., different levels in a gray scale or in another look-up-table - LUT).
From a temporal point of view, the term resolution is used (somehow improperly), in the case of movies or time lapses in general, to indicate the temporal distance between two frames or measurements. In techniques where the temporal resolution is not given directly from a temporal distance between subsequent measurements (e.g., pulsed time resolved pump-probe techniques), it can be used more properly as defined above.
The general exact definition given above does not allow assigning easily an exact value to the resolution, because the resolving power of an instrument in a given measurement would depend on so many things (physical limits, like the diffraction one both spatially and spectrally; signal to noise ratio; a priori knowledge of the sample, etc.). For this reason a "standard" value is often decided, which allows comparing different instruments, and this causes the so-many different definitions that can be found. E.g., in microscopy, a standard value is the distance from the center to the first minimum of the Airy function given the numerical aperture of an objective (NA), which gives the Abbe formula for resolution equal to 0.61/NA. In spectroscopy, when a spectrum is measured, it can be the full width at half maximum of the measured spectrum of strictly monochromatic light (i.e., a spectral line much smaller than the resolution itself). However, there are actually as many definition of “standard resolution” as there are types of instruments (and on “Charisma” I have seen this kind of definition).
I found a nice discussion on what is and what is not resolution (at least in microscopy) on the book "Introduction to Confocal Fluorescence Microscopy", Michiel Müller, edited by SPIE press (WA, USA), second edition (2006), page 14 and following. In particular, figure 1.15 illustrates that resolution and sampling should not be confused.
According to the Niquist theorem, the more indicated sampling given a certain resolution is two “points” per resolution value.

**Comment by Stefano-Luin** [comment]
Another thing: the resolution trade-off, for what I read or wrote, is not linked to the fact that you cannot "resolve" more than one or two things with an instrument... It is more linked to the fact that, usually, the better one kind of resolution is, the worse are the others. E.g., in microscopy, to have very high spatial resolution, usually you need to integrate more time or in any case you need more time to acquire an image.

**Comment by Zack-83** [comment]
>     * **Resolution interval (science)** == Minimum difference between two measurements so that they can be resolved (i.e., they can be considered different)
>       
>       * **Spatial resolution (microscopy)** == Minimum distance between two points so that they can be considered two separate points in a certain microscope with given experimental parameters
>         
>         * Lateral resolution as angle:  δθ=1.22⋅λ/D
>         * Lateral resolution as length: δr=0.61⋅λ/NA
>           (Abbe formula, derived from the Rayleigh criterion with the Kirchhoff, Debye and paraxial approximation)
>         * Axial resolution as length:   ²δz=2⋅n⋅λ/NA²
>       * **Spectral resolution (spectroscopy)** == Minimum distance between two very narrow peaks so that they can be seen as two separate peak
>         
>         * Spectral resolution as wavelength δλ=λ/(n⋅N)=RF⋅Δλ⋅WS/n
>         * Spectral resolution as wavenumber δν¯
>         * Spectral resolution as frequency  δν
>         * Spectral resolution as energy     δE
>       * **Radiometric resolution** == Minimum difference of irradiated energy to which can be (or are) given different "values" (e.g., different levels in a gray scale or in another look-up-table - LUT)
>       * **Temporal resolution** == Temporal distance between two frames or measurements (_common but somehow improper definition_). In techniques where the temporal resolution is not given directly from a temporal distance between subsequent measurements (e.g., pulsed time resolved pump-probe techniques), it can be used more properly as defined above.   = 1 / frame rate

Definitions updated. We can talk about whenever you want. Thanks to Stefano!

**Comment by StroemPhi** [comment]
The terms requested should actually be defined in another ontology that has a much broader scope, e.g. some optical device ontology. To my knowledge there does not exist such an ontology within OBO, as most such devices are defined in OBI already with some overlap to CHMO. So we could think about requesting these terms in either, but probably better to request in OBI.
