### ISSUE TITLE
[Docs] Why are there duplicate classes?

### ISSUE THREAD

**Issue by Zack-83** [NFDI4Chem/VibrationalSpectroscopyOntology#34]
Some fields seem to have the same meaning:

- "excitation wavelength" = "excitation wavelength setting";
- "groove density" = "groove density setting" = "diffraction grating"

I suggest to choose only one and choose one coherent labelling (with or without "... setting")

**Comment by StroemPhi** [comment]
Hi @Zack-83, thanks for raising this issue! 
These are not duplicates classe. (Please let's not speak of fields but of classes, because this is an ontology and not a metadata schema.) 

As you can see in the exact wording of the textual definition as well as in the super class of these terms in [vibso_terms.tsv](../blob/main/src/templates/vibso_terms.tsv), "groove density setting" (a [setting datum](https://terminology.nfdi4chem.de/ts/ontologies/obi/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FIAO_0000140&viewMode=All&siblings=false#)) is the piece of information/data needed to set the "groove density" (a [physical quality aka attribute/characteristic](https://terminology.nfdi4chem.de/ts/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001018#) of the **device** we call "diffraction grating". Assuming that the "groove density" of the "diffraction grating" device within a Raman spectrometer a  is not the same throughout time, because we can set it to different values, we are interested in the setting of a specific experiment. It might thus be valid to think about dropping the "groove density" class. The decision to model and label it this way depends on the OBO framwork as mentioned [here](https://nfdi4chem.github.io/VibrationalSpectroscopyOntology/design_patterns/) in the docs.

Similar with the other example you mention here. The "excitation wavelength" is the quality of the light source and "excitation wavelength setting" is the information needed to set this quality. Also here, it might be worth to ponder whether we really need this class, or if its already existing superclass [wavelength](https://terminology.nfdi4chem.de/ts/ontologies/pato/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPATO_0001242) might suffice and the fact that it is a wavelength used to exite the sample might probably be better modeled via a "exitation role" inhered in the light source device. 

I hope this clarifies things.

**Comment by StroemPhi** [comment]
closing this in favor of discussing this further in the respective issue trakcers #48 & #45
