### ISSUE TITLE
[Docs] add section to docs for checking ISO 18115-1/3 in NTR workflow 

### ISSUE THREAD

**Issue by StroemPhi** [NFDI4Chem/VibrationalSpectroscopyOntology#65]
We need to documents as a general workflow that we need:

- to check [ISOCD_18115-1_Revisions.pdf](https://drive.google.com/file/d/1odBI-VtN0N1Tb59dltAx-Fhhjcxl8IBV/view?usp=share_link)  for existing definitions of general spectroscopy terms needed in VIBSO
- to check [ISO_DIS_18115-3_E.pdf](https://drive.google.com/file/d/1xM0vNvgf25k9QXB1hxB6l0E3XfWvQL4Z/view?usp=share_link) for existing definitions of VISBO specific terms

**Comment by Zack-83** [comment]
Vorschlag: Klassifizierung nach Ampelsystem im Hinblick auf die Relevanz für die Berücksichtigung in der Ontologie

|ID|Preferred term label|Synonyms |Textual definition|Link to [CHARISMA Wiki equivalent]|Suggested parent term|Axiomatization|Examples|Notes|
|--|--------------------|---------|------------------|----------------------------------|---------------------|--------------|--------|-----|
|3.5.1  |anti-Stokes Raman scattering                |     |[def01] |  |3.5.16               |       |  |[^01] |
|3.5.2  |backscattering configuration                |     |[def02] |  |optical configuration|       |  |[^02] |
|3.5.3  |coherent anti-Stokes Raman scattering       |CARS |[def03] |  |3.5.1                |       |  |[^03.1] [^03.2] [^03.3] [^03.4] |
|3.5.4  |coherent Raman scattering microscopy        |CRS  |[def04] |  |scattering microscopy|       |  |[^04] |
|3.5.5  |coherent Stokes Raman scattering            |CSRS |[def05] |  |3.5.25               |       |  |[^05.1] [^05.2] [^05.3] [^05.4] |
|3.5.6  |confocal Raman microscopy                   |     |[def06] |  |3.5.17               |       |  |[^06] |
|3.5.7  |depolarization ratio                        |     |[def07] |  |intensity ratio      |       |  |[^07] |
|3.5.8  |electronic Raman scattering                 |     |[def08] |  |3.5.16               |       |  |[^08] |
|3.5.9  |enhancement factor                          |     |[def09] |  |intensity ratio      |       |  |[^09.1]; [^09.2] |
|3.5.10 |hyper-Raman scattering                      |     |[def10] |  |inelastic light scattering|  |  |[^10] |
|3.5.11 |polarized Raman spectroscopy                |     |[def11] |  |3.5.17               |       |  |[^11] |
|3.5.12 |Raman amplification                         |     |[def12] |  |intensity ratio      |       |  |[^12] |
|3.5.13 |Raman depth profiling                       |     |[def13] |  |3.5.14               |       |  |[^13] |
|3.5.14 |Raman mapping                       |Raman imaging|[def14] |  |mapping              |       |  |[^14] |
|3.5.15 |Raman optical activity              |ROA          |[def15] |  |optical activity     |       |  |[^15] |
|3.5.16 |Raman scattering                    |Raman effect |[def16] |  |inelastic light scattering|  |  |[^16] |
|3.5.17 |Raman spectroscopy                          |     |[def17] |  |optical spectroscopy |       |  |[^17] |
|3.5.18 |Raman tensor                                |     |[def18] |  |tensor               |       |  |[^18] |
|3.5.19 |Raman shift                                 |     |[def19] |  |energy difference    |       |  |[^19] |
|3.5.20 |resonance Raman spectroscopy                |RR   |[def20] |  |3.5.17               |       |  |[^20] |
|3.5.21 |rotational Raman spectroscopy               |     |[def21] |  |3.5.17               |       |  |[^21] |
|3.5.22 |spontaneous Raman spectroscopy              |     |[def22] |  |3.5.17               |       |  |[^22] |
|3.5.23 |spatially offset Raman spectroscopy         |SORS |[def23] |  |3.5.17               |       |  |[^23] |
|3.5.24 |stimulated Raman scattering                 |SRS  |[def24] |  |3.5.16               |       |  |[^24.1] [^24.2] |
|3.5.25 |Stokes Raman scattering                     |     |[def25] |  |3.5.16               |       |  |[^25] |
|3.5.26 |surface-enhanced Raman spectroscopy         |SERS |[def26] |  |3.5.17               |       |  |[^26] |
|3.5.27 |surface-enhanced Raman scattering           |SERS |[def27] |  |3.5.16               |       |  |[^27.1] [^27.2] [^27.3] |
|3.5.28 |surface-enhanced resonant Raman scattering  |SERRS|[def28] |  |3.5.16               |       |  |[^28] |
|3.5.29 |surface-enhanced resonant Raman spectroscopy|SERRS|[def29] |  |3.5.20               |       |  |[^29] |
|3.5.30 |tip-enhanced Raman spectroscopy             |TERS |[def30] |  |3.5.20               |       |  |[^30] |
|3.5.31 |tip-enhanced resonance Raman spectroscopy   |TERRS|[def31] |  |3.5.20               |       |  |[^31] |
|3.5.32 |transmission Raman spectroscopy             |     |[def32] |  |3.5.17               |       |  |[^32] |
|3.5.33 |resonant excitation profile                 |     |[def33] |  |                     |       |  |[^33] |
|3.5.34 |transmission configuration                  |     |[def34] |  |optical configuration|       |  |[^34] |
|3.5.35 |vibrational-rotational spectroscopy         |     |[def35] |  |optical spectroscopy |       |  |[^35] |

[CHARISMA Wiki equivalent]: https://wiki.charisma.ideaconsult.net/wiki/List_of_all_terms
[def01]: ## "Raman scattering (3.5.16) in which the emitted photon has higher energy than the incident photon"
[def02]: ## "optical configuration where the collected scattered light is in the opposite direction of the incident light"
[def03]: ## "multi-photon, third order nonlinear, wave mixing process that enhances the anti-Stokes Raman signal"
[def04]: ## "family of multi-photon microscopy techniques which use Raman active scattering modes of molecules"
[def05]: ## "multi-photon, third order nonlinear, wave mixing process that enhances the Stokes Raman signal"
[def06]: ## "Raman spectroscopy performed via a confocal optical microscopy set-up, in which a well-characterized mono-chromatic light is used to excite a sample and Raman scattered light is collected"
[def07]: ## "intensity ratio of the Raman scattering (3.5.16) perpendicular to the plane of polarization of the incident laser light to the polarization component of Raman scattering parallel to the polarization component"
[def08]: ## "Raman scattering (3.5.16) caused by electronic transitions of materials"
[def09]: ## "<TERS, SERS> ratio of the Raman signal intensity measured at a given wavenumber with the metallic probe or surface present to that in the absence of the probe or surface, scaled to equal numbers of scatterers"
[def10]: ## "Raman scattering caused by two-photon excitation where two photons of the source (probe laser) are practically converted to one photon of Raman scattered light and one phonon when interacting with matter"
[def11]: ## "Raman spectroscopy (3.5.17) where special attention is paid to the polarization state of the excitation and/or scattered light"
[def12]: ## "optical amplifiers based on Raman gain"
[def13]: ## "acquisition of Raman spectra as a function of depth or material removed by sputtering in order to obtain a depth representation of the spatial distribution of a particular molecular species (as indicated by the Raman effect (3.5.16))"
[def14]: ## "operation whereby the signal intensity or signal energy (band position) of a particular Raman vibrational mode or the intensity ratio of two Raman vibrational modes are mapped by undertaking Raman spectroscopy (3.5.17) while pointwise scanning the sample surface and subsequently evaluating each pixel of the image"
[def15]: ## "vibrational spectroscopic method that measures the small difference in intensity of Raman scattered right and left circularly polarized light due to molecular chirality"
[def16]: ## "inelastic scattering of electromagnetic radiation, characterized by a loss or gain in energy of the incident photons corresponding to a energy transition within the scatterer"
[def17]: ## "spectroscopy in which the radiation scattered from a sample illuminated with monochromatic radiation is characterized by an energy loss or gain arising from rotational, or vibrational mode excitations"
[def18]: ## "tensor that describes the relationship between the electric field vectors of incident and Raman scattered light for a specific Raman-active vibrational mode where the symmetry of the Raman tensor is related to the symmetry of the underlying vibrational mode"
[def19]: ## "energy difference between inelastically scattered photon and incident photon resulting via Raman effect (3.5.16) which is equal to the energy of the associated vibrational or rotational mode"
[def20]: ## "Raman spectroscopy (3.5.17) conducted under resonant conditions, where the incident or scattered light wavelength matches an optical absorption band of the sample, under these conditions the Raman scattering cross-section of particular modes are enhanced"
[def21]: ## "Raman scattering (3.5.16) caused by rotational transitions of molecules"
[def22]: ## "Raman spectroscopy that relies on random Raman scattering (3.5.16) of a proportion of incident photons"
[def23]: ## "variant of Raman spectroscopy using multiple Raman measurements from sample locations spatially offset from one another that are scaled and subtracted from one another to produce and collect/acquire Raman spectra representing subsurface and surface molecular species"
[def24]: ## "third order nonlinear phenomenon involving a second photon where the difference in the frequency of the coinciding photons matches the vibrational/rotational frequency to be excited"
[def25]: ## "Raman scattering (3.5.16) in which the scattered photon has lower energy than the incident photon"
[def26]: ## "spectroscopy using surface-enhanced Raman scattering (3.5.27)"
[def27]: ## "enhanced Raman scattering (3.5.16) observed for molecules in close proximity to a nano-scale roughened plasmonic metal surface or to metallic nanoparticles, where Raman scattering cross-sections are many orders of magnitude greater than for the same molecules in the absence of the rough plasmonic metal surface"
[def28]: ## "surface-enhanced Raman scattering in which the energy of the incident or scattered radiation is in resonance with an optical transition in the molecule"
[def29]: ## "spectroscopy using surface-enhanced resonant Raman scattering (3.5.28)"
[def30]: ## "spectroscopy using enhanced Raman scattering (3.5.16) with a plasmonically active metallic probe tip in close proximity to a sample surface illuminated with suitably polarized monochromatic light of appropriate wavelength"
[def31]: ## "spectroscopy involving a combination of tip-enhanced Raman scattering with resonance Raman spectroscopy (3.5.20)"
[def32]: ## "Raman spectroscopy whereby one side of a sample is illuminated, and the transmitted light is collected on the other side"
[def33]: ## "relationship between intensity of Raman scattering for a particular vibrational or rotational mode and the photon energy (wavelength) of the incident light"
[def34]: ## "optical configuration where the collected light propagates in the same direction as the incident light"
[def35]: ## "branch of molecular spectroscopy techniques, measuring signals caused by vibrational transitions of molecules"
[^01]: 
[^02]: Note 1 to entry: This is the typical configuration of a Raman spectrometer coupled with a microscope.
[^03.1]: Note 1 to entry: CARS signal is generated in samples due to third-order nonlinear susceptibility and requires three laser beams. A Stokes beam with frequency ωs, a pump beam with frequency ωp and a probe beam with frequency ωpr. When the photons of the beams interact, they produce an anti-Stokes frequency (ωpr +ωp −ωs), when the term (ωp −ωs) matches the vibrational frequency of the Raman resonance then the anti-Stokes frequency is enhanced producing an orders stronger Raman signal comparing to spontaneous Raman spectroscopy.
[^03.2]: Note 2 to entry: See also anti-Stokes Raman scattering (3.5.1).
[^03.3]: Note 3 to entry: It is a third order process as it is the cubic component of the Taylor series expansion of the nonlinear susceptibility.
[^03.4]: Note 4 to entry: coherent -Stokes Raman scattering (CSRS) (3.5.5) is the opposite of CARS.
[^04]: Note 1 to entry: Under the family of CRS are the techniques of coherent anti-Stokes Raman scattering (CARS) (3.5.3), CSRS (3.5.5) and stimulated Raman scattering (SRS) (3.5.24).
[^05.1]: Note 1 to entry: CSRS requires three laser beams, the anti-Stokes beam with frequency ωAs, a pump beam with frequency ωp and a probe beam with frequency ωpr. When the photons of the beams interact they produce a Stokes frequency (ωpr +ωp −ωΑs), w hen t he t erm (ωp −ωΑs) matches the vibrational frequency of the Raman resonance then the Stokes frequency is enhanced producing an orders stronger Raman signal comparing to spontaneous Raman spectroscopy.
[^05.2]: Note 2 to entry: See also Stokes Raman scattering (3.5.25).
[^05.3]: Note 3 to entry: It is a third order process as it is the cubic component of the Taylor series expansion of the nonlinear susceptibility.
[^05.4]: Note 4 to entry: CSRS is pronounced as “scissors”.
[^06]: 
[^07]: 
[^08]: 
[^09.1]: Note 1 to entry: The enhancement factor is the product of the contrast and the ratio of the volumes analysed without the probe and with the probe.
[^09.2]: Note 2 to entry: In TERS the enhancement is due to the presence of the probe and in SERS it is due to the presence of a surface that is typically metallic and contains nanoscale features.
[^10]: 
[^11]: Note 1 to entry: This is typically achieved using combinations of retardation plates (3.1.34), scrambler and polarizers (3.1.28) in the optical path.
[^12]: Note 1 to entry: See CARS (3.5.3) and SRS (3.5.24) as examples of Raman amplification.
[^13]: [SOURCE: adapted from ISO 14606:2015, 3.6]
[^14]: Note 1 to entry: Raman spectral mapping and Raman spectral imaging are terms that are also used.
[^15]: Note 1 to entry: The method probes biomolecular structure and behaviour in aqueous liquids.
[^16]: Note 1 to entry: Typically, monochromatic optical radiation is used to probe vibrational or rotational energy levels in a molecular or crystalline sample.
[^17]: [SOURCE: ISO/TS 80004‑13:2017, 3.3.1.6, modified replaced emitted by scattered]
[^18]: 
[^19]: Note 1 to entry: Raman shift is typically expressed in wavenumbers.
[^20]: 
[^21]: 
[^22]: Note 1 to entry: There is no enhancement of sensitivity. This is in contrast to stimulated Raman scattering (3.5.24).
[^23]: Note 1 to entry: The method is used for chemical analysis at a sub-surface level for example inside biological material or inside packaging.
[^24.1]: Note 1 to entry: The difference frequency sometimes called as “beat frequency”.
[^24.2]: Note 2 to entry: The SRS signal strength is linearly proportional to the concentration.
[^25]: Note 1 to entry: See anti-Stokes Raman scattering (3.5.1).
[^26]: Note 1 to entry: The acronym SERS is used for both surface-enhanced Raman scattering and spectroscopy.
[^27.1]: Note 1 to entry: The acronym SERS is used for both surface-enhanced Raman scattering and spectroscopy.
[^27.2]: Note 2 to entry: The enhancement is particularly strong for gold and silver surfaces of appropriate surface roughness, when excited by a laser at the correct wavelength.
[^27.3]: Note 3 to entry: Surface-enhanced Raman scattering is utilized via a tip-enhancement in TERS (3.5.30).
[^28]: Note 1 to entry: The acronym SERRS is used for both surface-enhanced resonant Raman scattering and spectroscopy.
[^29]: Note 1 to entry: The acronym SERRS is used for both surface-enhanced resonant Raman scattering and spectroscopy.
[^30]: Note 1 to entry: TERS provides higher scattering cross-section and higher spatial resolution than confocal Raman microscopy.
[^31]: 
[^32]: Note 1 to entry: This can be used for samples up to approximately 10 mm thick with the collected Raman signal representative of the bulk material. The thickness depends on the transmittance of the sample to the excitation light.
[^33]: 
[^34]: Note 1 to entry: Compare with backscattering configuration (3.5.2).
[^35]: Note 1 to entry: Raman and Infrared spectroscopy are the main representative techniques of this family, each technique being sensitive to different type of vibrations and provide complementary vibrational spectra.
## "Attribution"
ORCID:0000-0002-1595-3213|ORCID:0000-0001-7694-5519|ORCID:0000-0002-2239-3955

**Comment by StroemPhi** [comment]
closed in favor of #96
